config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'index', to: 'pages#index', as: :index
  get 'profile', to: 'pages#profile', as: :profile
  delete 'profile', to: 'bookings#destroy', as: "booking_destroy"


  resources :goods do
    resources :bookings, only: [:new, :create, :show]
  end

  resources :bookings, only: [:list, :index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :good
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/good.rb
class Good < ApplicationRecord
  DESIGNER = [
"Balenciaga",
"Bottega Veneta",
"Burberry",
"Celine",
"Chanel",
"Chloé",
"Cult Gaia",
"Dior",
"Dolce and Gabbana",
"Fendi",
"Givenchy",
"Gucci",
"Hermes",
"Jimmy Choo",
"Loewe",
"Louis Vuitton",
"Prada",
"Tory Burch",
"Valentino",
"Saint Laurent",
"David Heinemeier Hansson"
]
 CATEGORY = [
"Clutches",
"Crossbody Bags",
"Mini Bags",
"Shopper Bags",
"Shoulder Bags",
"Handle Bags",
"Tote Bags",
"Backpack"
]


  has_many_attached :photos
  belongs_to :user # posts in your item
  has_many :bookings
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  # has_many :users, through :bookings
  # bookings someone's item
  # has_many :reviews, through :bookings
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  include Pundit

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address, :phone_number,])

    # For additional in app/views/devise/registrations/edit.html.erb
    # devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :find, only: [:show, :update]

  def index
    policy_scope(Booking).order(created_at: :desc)
    @bookings = Booking.where(user_id: current_user)

    authorize @bookings
  end

  def show
    @good = @booking.good
    authorize @good
    authorize @booking

  end

  def new
    @good = Good.new
    @good = Good.find(params[:good_id])
    @booking = Booking.new
    authorize @booking
  end

  def create
    @good = Good.find(params[:good_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    authorize @booking



    @booking.good_id = @good.id
    @booking.value = (@booking.end_date - @booking.start_date).to_i * @good.price.to_i

    if @booking.save
      redirect_to good_booking_path(@good, @booking), notice: 'Your item was successfully booked.'
    else
      render :new
   end
  end

# this one is for listing all bookings of user? not based on reservations
  def list
    @bookings = Booking.where(user_id: user_session)
    authorize @booking
  end


  def update
    find
    @booking.status = true
    @booking.save
    redirect_to booking_path(@booking)

  end

  def destroy
    @booking = Booking.where(user_id: current_user.id).first
    authorize @booking
    @booking.destroy
    redirect_to profile_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :value, :user_id, :good_id)
  end

  def find
    @booking = Booking.find(params[:id])
    authorize @booking
  end
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show, :index, :root]
  before_action :find, only: [:show, :edit, :update, :destroy]

  def index

    if params[:designer].present? && params[:category].present?
      @goods = policy_scope(Good).where(designer: params[:designer], category: params[:category])
    else
      @goods = policy_scope(Good)
    end


    @good = Good.new


    @goods = @goods.geocoded #returns flats with coordinates

    @markers = @goods.map do |good|
      {
        lat: good.latitude,
        lng: good.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { good: good })
      }
     # .order(created_at: :desc)
   end
  end

  def new
    @good = Good.new
    authorize @good
  end

  def show
    # @good = Good.find(params[:id])
    @booking = Booking.new # This is so that we can have the Booking form in the show page
    authorize @good
  end

  def create
    @good = Good.new(good_params)
    @good.user = current_user

    authorize @good

    if @good.save
      redirect_to    root_path, notice: 'Your item was successfully created.'
    else
      render :new
   end
  end

  def edit
    authorize @good
  end

  def update
    @good.update(good_params)
    authorize @good
    redirect_to good_path(@good)
  end

  def destroy
    authorize @good
    @good.destroy
    redirect_to goods_path
  end
 private

  def find
    @good = Good.find(params[:id])
  end
  def good_params
    params.require(:good).permit(:name, :description, :category, :price, :designer, :address, :user_id, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home]
  def home
    @good = Good.new
    @goods = Good.all
  end

  def index
    @good = Good.new
    @goods = Good.all
  end

  def profile
    @bookings = Booking.where(user_id: current_user.id)
    @goods = Good.where(user_id: current_user.id)
    @user = User.find(current_user.id)

    unless @bookings.count == 0
      @next_booking = Booking.where(:user_id => current_user.id, :start_date => Date.today).all
      @next_booking = Booking.find(@next_booking.ids[0])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
  <h2>All my rent luxury goods</h2>

  <h4>My future bookings</h4>

  <ul >

    <% @bookings.each do |booking| %>
      <% if booking.start_date >= Date.today %>
                <% if booking.status == false %>
                <li>
                  <div >
                    <h2><%= booking.good.name %></h2>
                    <p>City: <strong><%= booking.good.address %></strong></p>
                    <p>Address: <strong><%= booking.good.address %></strong></p>
                    <p>Total price: <strong><%= booking.value %> €</strong></p>
                    <p>Starting date: <strong><%= booking.start_date.strftime('%A %d %B %Y') %> </strong></p>
                    <p>End date: <strong><%= booking.end_date.strftime('%A %d %B %Y') %> </strong></p>
                  </div>
                  <div>
                    <ul>
                      <li><strong>Wait for confirmation. Stay sharp</strong></li>
                    </ul>
                  </div>
                </li>
                <%# end %>

                <% else %>
                <li>
                <div>
                  <h2><%= booking.good.name %></h2>
                  <p>City: <strong><%= booking.good.address%></strong></p>
                  <p>Address: <strong><%= booking.good.address %></strong></p>
                  <p>Total price: <strong><%= booking.value %> €</strong></p>
                </div>
                <div>
                  <ul>
                    <li><strong>The booking is confirmed!</strong></li>
                  </ul>
                </div>
                </li>
                <% end %>
        <% end %>
    <% end %>
  </ul>

app/views/bookings/show.html.erb
<div class="show-good">
  <div class="row heading_show">
    <h2>My current booked luxury items</h2>
  </div>

  <div class="_card-show">
    <%= cl_image_tag @good.photos.first.key, crop: :fill %>
    <h4><%= @booking.good.name %></h4>
    <p>Total price: <strong><%= @booking.value %> €</strong></p>
    <p>Starting date: <strong><%= @booking.start_date.strftime('%A %d %B %Y') %> </strong></p>
    <p>End date: <strong><%= @booking.end_date.strftime('%A %d %B %Y') %> </strong></p>
    <p>Designer: <strong><%= @good.designer %> </strong></p>
    <p>Category: <strong><%= @good.category %> </strong></p>
  </div>
  <div style="margin-top: 40px; margin-bottom: 40px;">
 <div class="row d-flex justify-content-between _bnk">
    <%= link_to 'Back', :back, class: "btn btn-outline-secondary mr-5 pt-2" %>
    <%= link_to 'Continue shopping', goods_path, class: "btn btn-outline-secondary _button-gold-outline ml-6" %>
  </div>
  </div>
</div>

app/views/goods/_info_window.html.erb
<h4><%= good.name %></h4>
<p><%= good.address %></p>

app/views/goods/edit.html.erb
<div class="container _c-add-item">
  <h1 class="title _t-add-item", id="textprofile">Edit your item</h1>
  <%= render partial: 'shared/add-edit-good' %>
</div>

app/views/goods/index.html.erb
<div class=" allgoods">
<div class="col-2 pl-3 fil-b">
  <h4 class="filter-head pl-4 my-3 py-3">Designer</h4>
  <% Good::DESIGNER.each do |f| %>
     <ul class="filters pl-4"><li><%= f %></li></ul>
  <% end %>
  <h4 class="filter-head pl-4 my-3 py-3">Category</h4>
  <% Good::CATEGORY.each do |f| %>
     <ul class="filters pl-4"><li><%= f %></li></ul>
  <% end %>
  </div>
  <div class="cards   c-ind-b overflow-auto col-7">
    <% @goods.each do |good| %>
    <div class="card  c-body">
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path good.photos.first.key, crop: :fill %>')">
      </div>
      <div class="card-good-infos">
        <div>
          <h5><%= link_to good.name, good_path(good)%></h5>
          <p><%= good.category%></p>
          <h6><em><%= good.designer%></em></h6>
        </div>
          <h6 class="card-good-pricing mb-3"><%=good.price%>€/day</h6>
        </div>
      </div>
    <% end %>
  </div>

  <div id="map"  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="pk.eyJ1IjoibWFyaWlhZGMiLCJhIjoiY2s3NHZ2NnQyMDlrbzNlbnQ2cnFrdWNpZiJ9.ZYmsU_WNi11Tl2xL_v-hfw" class="container col-3 mx-0">
  </div>
</div>

app/views/goods/new.html.erb
<div class="container _c-add-item">
  <h1 class="title _t-add-item", id="textprofile">Add your item</h1>

<%= render partial: 'shared/add-edit-good' %>

</div>

app/views/goods/show.html.erb
<div class="page">
  <%= render partial: 'shared/carousel'%>
  <div class="container _title">
    <%= @good.name %>
  </div>
  <div class="container _body mt-4">
    <div class="description ">
      <div class="card-good-infos">
     <p><em> <%= @good.designer %> </em></p>
     <p id="price"><strong> <%= @good.price %></strong> €/day</p>
     </div>
      <p><%= @good.description %></p>
    </div>
    <div class="container col-md-4 _dates mb-4 ">
      <%= render partial: 'shared/dates' %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="viewport" content="width=device-width, initial-scale=1">


    <title>Glamavenue</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
  <% if user_signed_in? %>
    <%= render partial: 'shared/navbar' %>
  <% else %>
  <%= render partial: 'shared/navlogout' %>
  <% end %>
    <!-- <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> -->

    <%= yield %>
    <%= render partial:'shared/footer' %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/_cards.html.erb
   <h5>Booking with Glamavenue</h5>
    <div class="cards">
      <div class="card">
        <%= image_tag "chat.svg", alt: "chat" %>
        <h5>24/7 customer support</h5>
        <p>Day or night, we’re here for you. Talk to our support team from anywhere in the world, any hour of day.</p>
      </div>
      <div class="card">
        <%= image_tag "designer.svg", alt: "designer" %>
        <h5>Only top designers</h5>
        <p>From the runways and priovate collectors into your wardrobe - only top luxury items!</p>
      </div>
      <div class="card">
        <%= image_tag "delivery.svg", alt: "delivery" %>
        <h5>Fast delivery</h5>
        <p>Fast delivery 7 days a week - order today befor 4 pm, receive tomorrow before 11 am!</p>
      </div>
    </div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://source.unsplash.com/collection/4404440/1600x900);">

  <div class="container banner-search">
    <%= render partial: 'shared/search' %>
  </div>
</div>

<div class="container">
  <div class="outer-cards">
    <%= render partial: 'shared/cards' %>
  </div>
  <div class="container">
    <h5></h5>
    <p></p>
  </div>
</div>

app/views/pages/profile.html.erb
<div class="mx-5">
    <div>
    <div>
      <h3 class="mt-4", id="textprofile">My Profile</h3>
    </div>
      </div>

      <div class="mb-4">
        <!-- this div contains all the body below h2 -->
        <div>
        <!-- sidebar -->
          <div class="d-flex">
            <!-- container for card of profile -->
            <div class="card  _user-info" style="width: 23rem;">
            <img src="https://www.historyisfun.org/wp-content/uploads/2018/09/John-Smith-picture.jpg" class="card-img-top" alt="">
              <div class="card-body _profile-card-body" id="text-vertical">
                <h6>Name</h6>
                <p class="card-text"><%= @user.first_name %> <%= @user.last_name %></p>
                <h6>Address</h6>
                <p class="card-text"><!-- <i class="fas fa-map-marker-alt profile-marker"></i> -->  <%= @user.address %></p>
                <h6>Contact</h6>
                <p class="card-text"><%= @user.phone_number %></p>
                <h6>Email</h6>
                <p class="card-text"><%= @user.email %></p>
                <br>
                <br>
                <p href="#" class="btn btn-outline-secondary _button-gold mx-auto" id="profilebutton">Edit Profile</p>
              </div>
            </div>

        <div style="width: 100%">
          <div class="d-flex">

            <% if @bookings.count == 0 %>
              <div class="card ml-4 mt-2" style="width: 20rem; height: 14rem">
                <div class="card-body" id="shadow">
                  <h5 id="textprofile"> Upcoming Order</h5>
                  <h6 id="textprofile"> You have no orders scheduled</h6>
              <p class="card-text">
                  <%= link_to 'See Orders', goods_path, id:"profilebutton", class: "btn btn-outline-secondary _button-gold mb-0" %> </p>
                </div>
              </div>
            <% else %>

            <div class="card ml-4 mt-2" style="width: 20rem; height: 14rem">
              <div class="card-body" id="shadow">
                <h5 id="textprofile">Upcoming Order</h5>
                <br>
                <h6> <%= @next_booking.good.name %></h6>
                <h6> <%= @next_booking.start_date.strftime('%A %d %B %Y') %></h6>
            <p class="card-text">
                <%= link_to 'See Details', good_booking_path(@next_booking.good_id, @next_booking), id:"profilebutton", class: "btn btn-outline-secondary _button-gold mb-0" %></p>
              </div>
            </div>

            <% end %>

            <div class=" ml-4 mt-2" style="width: 20rem; height: 14rem">
              <div class="" >

            <!-- <h1>Pie Chart</h1>
               <div id="pie" style="height: 100%;"></div>
                <script>
                 new Chartkick.PieChart("pie", [["Blueberry",44],["Strawberry",23],["Banana",22],["Apple",21],["Grape",13]], {download: "pie"});
                </script>
              </div> -->
               <!--  < % if @goods.count == 0  %>
                  <p>< % = @goods.count %> <br> <strong>Rental Items</strong></p>
                  <a href="#" class="btn btn-outline-secondary _button-gold mx-auto" id="profilebutton">Add new item</a>

                < % elsif @goods.count == 1  %>
                  <p>< %= @goods.count %> <br> <strong>Rental Item</strong></p>
                  <a href="#" class="btn btn-outline-secondary _button-gold mx-auto" id="profilebutton">Add new item</a>
                < % else %>
                  <p>< %= @goods.count %> <strong>Rental Items</strong></p>
                  <a href="#" class="btn btn-outline-secondary _button-gold mx-auto" id="profilebutton">My Goods list</a>
                < % end %> -->
              </div>
            </div>
          </div>
              <h5 class="m-4">My Items</h5>
            <div class="overflow-auto ml-4" style="width: 100%; height: 10rem">
            <!-- My goods list -->
            <% @goods.each do |good| %>
            <div class="notification" >

              <img src='<%= cl_image_path good.photos.first.key, crop: :fill %>' class="avatar-large"></img>
              <div class="notification-content" id="shadow">
                <h6 class="myitems"><small><%=link_to good.name, good_path(good)  %></small></h6>
             <!--    <p><%= good.description %></p> -->
              </div>
              <div class="notification-actions">
                <%= link_to edit_good_path(good) do %>Edit<i class="fas fa-pencil-alt fa-lg"></i><% end %>

                <%= button_to good_path(good), method: :delete, data: {confirm: "Are sure?"} do%>
                  <i class="far fa-trash-alt fa-lg"> </i>
                <% end %>
                <!-- <a href="#">Delete </i></a> -->
              </div>
            </div>
            <% end %>
          </div>


          <% if @bookings.count == 0 %>

          <h5 class="m-4" id="textprofile">You have No Orders Scheduled</h5>

          <% else %>

          <h5 class="m-4" id="textprofile"> My Orders Awaiting Confirmation</h5>
          <div class="overflow-auto ml-4" style="width: 100%; height: 10rem">

            <!-- My goods list -->
            <% @bookings.each do |booking| %>
            <div class="notification" >
              <% if booking.status == false %>
                <% good = Good.find(booking.good_id)  %>
                <img src='<%= cl_image_path good.photos.first.key, crop: :fill %>' class="avatar-large" />
                <div class="notification-content">
                  <h6><small><%= link_to good.name, good_booking_path(@next_booking.good_id, @next_booking) %></small></h6>
                  <h6><small> <%= booking.start_date.strftime('%A %d %B %Y') %></small></h6>
             <!--    <p><%= good.description %></p> -->
              </div>
              <% end %>
              <div class="notification-actions">

                <% if booking.status == false %>
                      <h6 id="textprofile">Unconfirmed <i class="fas fa-minus-circle fa-lg"></i></h6>
                <% else %>
                      <h6 id="textprofile">Confirmed! <i class="fas fa-check-circle fa-lg"></i></h6>
                <% end %>

                  <%= button_to booking_destroy_path, method: :delete do %>
                    <i class="far fa-trash-alt "></i>
                  <% end %>
              </div>
            </div>

            <% end %>
          </div>
          <% end %>
        </div>
     </div>
    </div>
      <!-- contains center of page -->
    </div>
</div>

app/views/shared/_add-edit-good.html.erb
  <div class="row _r-add-item">
    <div class="col-5">
      <%= simple_form_for [@good] do |f| %>
      <div class="form-inputs">
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :price %>
        <%= f.input :photos, as: :file, input_html: { multiple: true }  %>
        <%= f.input :address %>

        <%=  f.input :designer, collection: Good::DESIGNER %>
        <%=  f.input :category, collection: Good::CATEGORY %>
        <div class="row d-flex justify-content-between">
          <%= link_to "Cancel", root_path, class: "btn btn-outline-secondary ml-3 mb-2" %>
        <%= f.submit "Save", class: "btn btn-outline-secondary _button-gold mr-3 mb-2" %>

        </div>
      </div>


      <% end %>

<!--       < %= link_to "Cancel", root_path, class: "btn-outline-secondary ml-3 mb-2" %>
 -->
    </div>

    <div class="col-1"></div>
    <div class="col-6">
      <%= image_tag "online.svg", class:"mx-auto d-block", alt: "online", width: "80%", id:"online" %>
    </div>
  </div>

app/views/shared/_cards.html.erb
   <h4>Booking with GlamAvenue</h4>
    <div class="cards _cards-home">
      <div class="card _card-home">
        <%= image_tag "chat.svg", alt: "chat" %>
        <h5>24/7 customer support</h5>
        <p>Day or night, we’re here for you. Talk to our support team from anywhere in the world, any hour of day.</p>
      </div>
      <div class="card _card-home">
        <%= image_tag "designer.svg", alt: "designer" %>
        <h5>Only top designers</h5>
        <p>From the runways and priovate collectors into your wardrobe - only top luxury items!</p>
      </div>
      <div class="card _card-home">
        <%= image_tag "delivery.svg", alt: "delivery" %>
        <h5>Fast delivery</h5>
        <p>Fast delivery 7 days a week - order today befor 4 pm, receive tomorrow before 11 am!</p>
      </div>
    </div>

app/views/shared/_dates.html.erb
  <!-- <div class="container w-25"> -->
  <h5 id="dates">Add dates</h5>
  <%= simple_form_for [@good, @booking] do |f| %>
 <!--    <= f.input :url %>
    <= f.input :name %> -->
    <%= f.input  :start_date, as: :string, required: false, input_html: { id: "start_date"} %>
    <%= f.input :end_date, as: :string, required: false, input_html: { id: "end_date"} %>
    <%=f.submit 'Add Booking', class: "btn btn-outline-secondary _button-gold w-100" %>
  <% end %>
  <div class="mt-3" id="show-price">


  </div>


<!-- <script>

  let endDateElement = document.querySelector('#start_date');

  endDateElement.addEventListener("input", function() {
    event.preventDefault();

    // setTimeout(function(){

      endDateElement = document.querySelector('#start_date').value;
      let datesString = endDateElement.split(" to ");

      let startString = datesString[0].split("-");

      if (!datesString[1]) {
        return;
      }

      let endString = datesString[1].split("-");

      let startDate = new Date(startString[0], startString[1], startString[2]);
      let endDate = new Date(endString[0], endString[1], endString[2]);

      let days = Math.round((endDate - startDate)/(1000*60*60*24));
      let priceDay = document.getElementById('price').innerText.split(" ")[0];

      let totalPrice = days * priceDay ;  // in js.erb you can use ruby code. use that for the price instead of querys

      let paramaterTotal = document.getElementById('show-price')
      let html = `<strong><p>Total price: ${totalPrice} $</p></strong>`

      paramaterTotal.innerHTML = html;

    // }, 2000);

  });



</script>
 -->

app/views/shared/_footer.html.erb
<footer>
<div class="footer">
  <div class="container _box">
    <div class="icons">
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
    <div class="links">
      <a href="#"> About us </a>
      <a href="#"> Contact us </a>
    </div>
    <div class="copyrights">
      <a href="#">© GlamAvenue 2020</a>
    </div>
  </div>
</div>
</footer>

app/views/shared/_navbar.erb
<!-- <nav class="navbar navbar-light bg-light">
  <a class="navbar-brand">GlamAvenue</a>
  <form class="form-inline">
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </form>
</nav>
 -->
<nav class="navbar navbar-light bg-light main" id="nav-shared">
  <%= link_to 'GlamAvenue' ,root_path, class: "navbar-brand ml-5" %>




<div class="right-side">
<div class="cntr">
  <div class="cntr-innr">
    <label class="search" for="inpt_search">
      <input id="inpt_search" type="text" />
    </label>
  </div>
</div>
<div class="cart mx-3">
  <i class="fas fa-shopping-cart"></i>
</div>
<div class="dropdown mr-5">
  <a class="btn dropdown" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <i class="far fa-user-circle" id="profile"></i>
  </a>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
    <a class="dropdown-item" href="#">Profile</a>
    <a class="dropdown-item" href="#">Add booking</a>
    <a class="dropdown-item" href="#">Create item</a>
    <a class="dropdown-item" href="#">Sign Out</a>
  </div>
</div>
</div>
 </nav>

app/views/shared/_navbar.html.erb
<!-- <nav class="navbar navbar-light bg-light">
  <a class="navbar-brand">GlamAvenue</a>
  <form class="form-inline">
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </form>
</nav>
 -->
<nav class="navbar navbar-light bg-light main" id="nav-shared">
  <%= link_to 'GlamAvenue' ,root_path, class: "nav-br-logo ml-5" %>
  <div class="right-side">
    <div class="cntr">
      <div class="cntr-innr">
        <label class="search _nav-search" for="inpt_search">
          <input id="inpt_search" type="text" />
        </label>
      </div>
    </div>
    <div class="cart mx-3">
      <i class="fas fa-shopping-cart"></i>
    </div>
    <div class="dropdown mr-5">
      <a class="btn dropdown" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="far fa-user-circle" id="profile"></i>
      </a>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
        <%= link_to 'Profile', profile_path, class: "dropdown-item" %>
        <%= link_to 'Add booking', goods_path, class: "dropdown-item" %>
        <%= link_to 'Add item', new_good_path, class: "dropdown-item" %>
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_navlogout.erb
<nav class="navbar navbar-light bg-light main" id="nav-shared">
  <%= link_to 'GlamAvenue' ,root_path, class: "navbar-brand ml-5" %>




  <div class="right-side">
       <%= link_to 'Sign Up' , new_user_path, class: "text-navbar" %>
    <%= link_to 'Log In', existing user path, class: "text-navbar" %>

  </div>
</nav>